### ISSUE TITLE
Unable to run studio.exe on Windows 7 x64

### ISSUE THREAD

**Issue by kingofoz** [nem0/lumixengine_data#102]
I double clicked LumixStudio and get a crash:
![crash](https://cloud.githubusercontent.com/assets/9476604/26551325/8ffbdc4c-44b4-11e7-9981-ca48955f82ff.png)
Any idea?

**Comment by nem0** [comment]
Is there anything in error.log?

**Comment by kingofoz** [comment]
Nope. It is empty.

**Comment by nem0** [comment]
I've updated the executables - crash callstack should now be correct. Please try it and let me know.

**Comment by kingofoz** [comment]
Hi @nem0 
I have tried the latest version you updated. No luck. The error remains.

**Comment by nem0** [comment]
Could you please upload minidump.dmp here?

**Comment by kingofoz** [comment]
Hi @nem0 
I uploaded it, please check.

[minidump.zip](https://github.com/nem0/lumixengine_data/files/1038458/minidump.zip)

**Comment by nem0** [comment]
It seems to crash when initializing bgfx while waiting for a semaphore. I have no idea what could cause that.  Lumix is compiled with 9 months old version of bgfx, I will try to update, it might help.

**Comment by kingofoz** [comment]
OK. Please let me know when do that so I can have a try.

**Comment by nem0** [comment]
Finally I resolved the issue with new bgfx version and updated everything. Hopefully it fixes the issue.

**Comment by nem0** [comment]
Hi, is this still not resolved?

**Comment by luckyycode** [comment]
Maybe that will help, but I had the same error (empty log and empty crash stack) when I was trying to launch LumixStudio from archive or from non-standard drive.
