### ISSUE TITLE
drawQuadEx() undefined ?

### ISSUE THREAD

**Issue by timbaker** [nem0/lumixengine_data#105]
Sorry if I'm being dense, but pipelines/hdr_dof_fxaa/hdr_dof_fxaa.lua calls a function that doesn't seem to be defined anywhere, drawQuadEx().  I see drawQuad() in pipeline.cpp.

**Comment by nem0** [comment]
Sorry for not responding sooner, it seems github is yet again not sending me emails. You are right, I have to investigate how this happened.

**Comment by nem0** [comment]
drawQuadEx is now defined. However bloom is not 100% correct, it seems like I committed some unfinished version, and I can't find the finished one. I have to finish it again.
