### ISSUE TITLE
IBL

### ISSUE THREAD

**Issue by nem0** [nem0/lumixengine_data#43]

**Comment by nem0** [comment]
closing this because of https://github.com/nem0/LumixEngine/issues/962

**Comment by dragonCASTjosh** [comment]
you may want to add something like IBL baker or cmft to pre-filter the ibl, If you can pre-filter the IBL and a irridiance map then a fully-prefiltered IBL system would be extremely fast

**Comment by nem0** [comment]
it's already in #903, I should probably clean up the issues a bit
