### ISSUE TITLE
Grass should stop moving when Lumix Engine is not in focus.

### ISSUE THREAD

**Issue by PeaceSells50** [nem0/lumixengine_data#70]
Stealing cycles from other applications.

**Comment by nem0** [comment]
FPS is lowered to 5 when Lumix is not in focus. If I remember correctly this was inspired by Unity.

**Comment by PeaceSells50** [comment]
What are the advantages of Unity doing something like this?

**Comment by nem0** [comment]
It does not waste so much power and it does not look stuck.
