### ISSUE TITLE
Godrays

### ISSUE THREAD

**Issue by nem0** [nem0/lumixengine_data#73]
http://http.developer.nvidia.com/GPUGems3/gpugems3_ch13.html
http://fabiensanglard.net/lightScattering/

**Comment by dragonCASTjosh** [comment]
It seams you are taking a screen space approach. I'd personally recommend looking into volumetric solutions for better results :)

**Comment by nem0** [comment]
There is no problem in having both. This is much simpler, quite fast and suitable for my game, that's why I am making it first.

**Comment by dragonCASTjosh** [comment]
fair enough :)

**Comment by nem0** [comment]
closed via e4accf59b8e7146bcba7f8eccff00299907aea14
